version: "3.8"
services:
  db:
    container_name: "mongo-blogs"
    image: mongo:7.0
    ports:
      - 27017:27017
    env_file:
      - .env
    networks:
      - workdown-blogs
    volumes:
      - /var/data/mongo:/data/db
networks:
  workdown-blogs:
